version: '3.8'

services:
  db:
    image: postgres
    container_name: db
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - $HOME/docker/volumes/postgres:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: always

  sidekiq:
    image: ruby:3.1.0
    container_name: sidekiq
    restart: always
    working_dir: /var/www/medical_exams
    volumes:
      - .:/var/www/medical_exams:Z
    command: bash -c "bundle && sidekiq -r ./config/sidekiq.rb -c 5"
    depends_on:
      - redis

  server:
    build: .
    container_name: medical_exams
    hostname: medical_exams
    ports:
      - "3000:3000"
    restart: always
    environment:
      - BUNDLE_PATH=vendor/bundle
      - BUNDLE_DISABLE_SHARED_GEMS=1
    working_dir: /var/www/medical_exams
    volumes:
      - .:/var/www/medical_exams:Z
    command: >
      bash -c "rake db:create db:migrate
      && ruby server.rb"

networks:
  default:
      name: exam_app
