#!/bin/bash

echo '------ building -----------'
echo

docker-compose build

echo
echo '------ build finished -----'
echo
echo '------ starting the app ---'
echo

docker-compose up

echo
echo '------ finishing ----------'
